// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlgiogIv8a4104nT8pHOhejGJXcuAL44E',
    appId: '1:1099496840630:web:577b8d77949d19b160f517',
    messagingSenderId: '1099496840630',
    projectId: 'attendly-dd63f',
    authDomain: 'attendly-dd63f.firebaseapp.com',
    storageBucket: 'attendly-dd63f.firebasestorage.app',
    measurementId: 'G-N46G08LV8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNxqcy6h9eTN8wuDLJC7UwEzO2S_KO2CQ',
    appId: '1:1099496840630:android:83f08a7f93e670e560f517',
    messagingSenderId: '1099496840630',
    projectId: 'attendly-dd63f',
    storageBucket: 'attendly-dd63f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqA96trXpAwYoUxs7O-jNpK6AqD-Bw1d0',
    appId: '1:1099496840630:ios:2eb1d97d381bd29760f517',
    messagingSenderId: '1099496840630',
    projectId: 'attendly-dd63f',
    storageBucket: 'attendly-dd63f.firebasestorage.app',
    iosBundleId: 'com.example.attendly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqA96trXpAwYoUxs7O-jNpK6AqD-Bw1d0',
    appId: '1:1099496840630:ios:2eb1d97d381bd29760f517',
    messagingSenderId: '1099496840630',
    projectId: 'attendly-dd63f',
    storageBucket: 'attendly-dd63f.firebasestorage.app',
    iosBundleId: 'com.example.attendly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlgiogIv8a4104nT8pHOhejGJXcuAL44E',
    appId: '1:1099496840630:web:13f991e24dd70b1760f517',
    messagingSenderId: '1099496840630',
    projectId: 'attendly-dd63f',
    authDomain: 'attendly-dd63f.firebaseapp.com',
    storageBucket: 'attendly-dd63f.firebasestorage.app',
    measurementId: 'G-JDPNEYHZ4W',
  );
}
